services:
  frontend:
    build:
      context: ./shoplify-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./shoplify-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:5000

  backend:
    build:
      context: ./shoplify-backend
    ports:
      - "5000:5000"
    volumes:
      - ./shoplify-backend:/app
      - /app/obj
      - /app/bin
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=shoplifyecommercebackendwebsite
      - Jwt__Issuer=http://localhost:5000
      - ConnectionStrings__shoplify-be=Host=db;Database=shoplify-db;Port=5432;Username=postgres;Password=root
      - FileStorage__Provider=Local
      - FileStorage__BasePath=/app/Storage

  db:
    image: postgres:18
    container_name: shoplify-db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
    - "5632:5432"
    volumes:
    - shoplify_postgres_data:/var/lib/postgresql

volumes:
  shoplify_postgres_data:
    name: postgres_data_shoplify